/*
 * JS for DINS generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'a0951686-3ab8-4517-8f67-74268169d267';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "l1",
    "location": "l1.html"
}, {
    "name": "SIGNUP",
    "location": "SIGNUP.html"
}, {
    "name": "DINS",
    "location": "DINS.html"
}];

function DINS_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_8': 'DINS_mobilebutton_8',
        'mobilelabel_7': 'DINS_mobilelabel_7',
        'mobiletextinput_2': 'DINS_mobiletextinput_2',
        'mobiletextinput_3': 'DINS_mobiletextinput_3',
        'mobilebutton_4': 'DINS_mobilebutton_4',
        'mobileimage_5': 'DINS_mobileimage_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["DINS_restservice1_onbeforesend_mapping_0"] = {
        "homeScreen": "DINS",
        "directions": [

        {
            "from_name": "DINS",
            "from_type": "UI",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['mobiletextinput_2:text']",
                "target": "$['parameters']['username']"

            },

            {

                "source": "$['mobiletextinput_3:text']",
                "target": "$['parameters']['password']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.restservice1 = Apperyio.datasources.restservice1 = new Apperyio.DataSource(insert_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["DINS_restservice1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("DINS");
        },
        "onSuccess": function(data) {
            Apperyio.navigateTo('l1', {
                transition: 'flip',
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert("username or passsword invalid");
        }
    });

    Apperyio.CurrentScreen = 'DINS';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var DINS_onLoad = function() {
            DINS_elementsExtraJS();

            DINS_deviceEvents();
            DINS_windowEvents();
            DINS_elementsEvents();
        };

    // screen window events


    function DINS_windowEvents() {

        $('#DINS').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function DINS_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function DINS_elementsExtraJS() {
        // screen (DINS) extra code

    };

    // screen elements handler


    function DINS_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#DINS_mobileheader [name="mobilebutton_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('SIGNUP', {
                        transition: 'pop',
                        reverse: false
                    });

                }
            },
        }, '#DINS_mobileheader [name="mobilebutton_8"]');

        $(document).off("click", '#DINS_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        restservice1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#DINS_mobilecontainer [name="mobilebutton_4"]');

    };

    $(document).off("pagebeforeshow", "#DINS").on("pagebeforeshow", "#DINS", function(event, ui) {
        Apperyio.CurrentScreen = "DINS";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    DINS_onLoad();
};

$(document).off("pagecreate", "#DINS").on("pagecreate", "#DINS", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    DINS_js();
});