/*
 * JS for l1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'a0951686-3ab8-4517-8f67-74268169d267';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "l1",
    "location": "l1.html"
}, {
    "name": "SIGNUP",
    "location": "SIGNUP.html"
}, {
    "name": "DINS",
    "location": "DINS.html"
}];

function l1_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'l1_mobilebutton_2'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["l1_restservice5_onsuccess_mapping_0"] = {
        "homeScreen": "l1",
        "directions": []
    };

    Apperyio.mappings["l1_restservice5_onbeforesend_mapping_0"] = {
        "homeScreen": "l1",
        "directions": [

        {

            "to_name": "restservice5",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.restservice3 = Apperyio.datasources.restservice3 = new Apperyio.DataSource(insert_logout_service, {
        "onBeforeSend": function(jqXHR) {},
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("l1");
        },
        "onSuccess": function(data) {
            try {
                restservice3.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.restservice5 = Apperyio.datasources.restservice5 = new Apperyio.DataSource(insert_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["l1_restservice5_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("l1");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["l1_restservice5_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.restservice6 = Apperyio.datasources.restservice6 = new Apperyio.DataSource(insert_userdetails_read_service, {
        "onBeforeSend": function(jqXHR) {},
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("l1");
        },
        "onSuccess": function(data) {},
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'l1';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var l1_onLoad = function() {
            l1_elementsExtraJS();

            l1_deviceEvents();
            l1_windowEvents();
            l1_elementsEvents();
        };

    // screen window events


    function l1_windowEvents() {

        $('#l1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function l1_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function l1_elementsExtraJS() {
        // screen (l1) extra code

    };

    // screen elements handler


    function l1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#l1_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        restservice3.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    Apperyio.navigateTo('DINS', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#l1_mobilecontainer [name="mobilebutton_2"]');

    };

    $(document).off("pagebeforeshow", "#l1").on("pagebeforeshow", "#l1", function(event, ui) {
        Apperyio.CurrentScreen = "l1";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    l1_onLoad();
};

$(document).off("pagecreate", "#l1").on("pagecreate", "#l1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    l1_js();
});