/*
 * JS for SIGNUP generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'a0951686-3ab8-4517-8f67-74268169d267';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "l1",
    "location": "l1.html"
}, {
    "name": "SIGNUP",
    "location": "SIGNUP.html"
}, {
    "name": "DINS",
    "location": "DINS.html"
}];

function SIGNUP_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobiletextinput_2': 'SIGNUP_mobiletextinput_2',
        'mobiletextinput_3': 'SIGNUP_mobiletextinput_3',
        'mobiletextinput_4': 'SIGNUP_mobiletextinput_4',
        'mobiletextinput_5': 'SIGNUP_mobiletextinput_5',
        'mobilebutton_7': 'SIGNUP_mobilebutton_7'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["SIGNUP_restservice7_onsuccess_mapping_0"] = {
        "homeScreen": "SIGNUP",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.restservice7 = Apperyio.datasources.restservice7 = new Apperyio.DataSource(insert_login_service, {
        "onBeforeSend": function(jqXHR) {},
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("SIGNUP");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["SIGNUP_restservice7_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'SIGNUP';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var SIGNUP_onLoad = function() {
            SIGNUP_elementsExtraJS();

            SIGNUP_deviceEvents();
            SIGNUP_windowEvents();
            SIGNUP_elementsEvents();
        };

    // screen window events


    function SIGNUP_windowEvents() {

        $('#SIGNUP').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function SIGNUP_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function SIGNUP_elementsExtraJS() {
        // screen (SIGNUP) extra code

    };

    // screen elements handler


    function SIGNUP_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#SIGNUP").on("pagebeforeshow", "#SIGNUP", function(event, ui) {
        Apperyio.CurrentScreen = "SIGNUP";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    SIGNUP_onLoad();
};

$(document).off("pagecreate", "#SIGNUP").on("pagecreate", "#SIGNUP", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    SIGNUP_js();
});